### ISSUE TITLE
Migration Script for Old Data

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-inventory#113]
With the introduction (and dependency) of `type` with the latest RC it has lead to the list command breaking for old data that does have the `type` key.

Can we get a script that will check/migrate existing data for validity? It is out of the question to re-import the data as modifications have already been made.

**Comment by DavidMarchant** [comment]
Just a note to self for when I get back to this: This will be an external script (in the `scripts/` directory) that will check that each file in the store has - as top level keys (#119) - 
1) 'name' = [filename]
2) 'mutable' = {} (at least, can be populated)
3) 'type' = [type]
We are also playing with the idea of having a 'primary group' within 'mutable' be required.

The script will need to load the yaml of each file as a hash, 'move it up a level' if the keys are nested (as per #119) and have some logic to add a type. This logic will likely be 'assign `server` if `lshw` and `lsblk` keys exist, else assign `switch`.

**Comment by DavidMarchant** [comment]
Additionally:
a) We should consider calling the script in the `postinst` of the RPM installation to automatically update old data to a valid format
b)  Leading on from this - we should have data files contain a version number such that the state of the data doesn't need to be inferred from it's qualities but instead from the state of `flight inventory` when it was created validly. This will allow us more widely applicable and more automated migration process.
