### ISSUE TITLE
Handling of Type

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-inventory#114]
Type is required for the list command to work. In the event of manual creation of an asset there will be an error with list if the asset does not have a type, therefore:
- A modify command for type would come in handy for bulk adding/editing the type of assets
- Removal/better handling of the type dependency in list would allow for existing data (#113) to work without issue (e.g. if there is no type, assume type is "unclassified")

**Comment by DavidMarchant** [comment]
From IRL chat: we've come to the conclusion that form this point we can go down one of two routes: Enforce data validity as a soft requirement or as a hard requirement

(for reference as of #119 data is valid if it's a valid yaml hash with name, type and (possibly empty) mutable keys. Also we're toying with the idea of making a primary group necessary as well)
 
I feel that a hard requirement is the way to go - ensuring data be in the correct format will improve program stability going forward, allow us to effectively add new data requirements as they arise and give more trust when interfacing `show` output to external programs.
What this will consist of is simply a general check on the targeted assets when commands are being executed. On failure, if it's a modifying command a warning should be printed - else if it's any other type of command execution (inc. `list`) should abort & the user should be informed of the specific issue ( & possibly pointed to our data migration script #113).

This will need to be confirmed closer to the date. 

A data-migration script will be created as of #113 regardless.

**Comment by DavidMarchant** [comment]
Ok change of plan - we're treating all assets without a type as being servers until further notice - please see https://github.com/openflighthpc/flight-inventory/pull/129/commits/0a476c357f219f5bd4c83cff1eac21ac761d2201
