### ISSUE TITLE
Primary Key Usage

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-inventory#119]
In the storage data for an asset we see:
```
node001:
  name: node001
```
This would be in `var/store/node001.yaml`.

What is the purpose of the top-level key? Does `node001:` get used for something?

It feels like it could just be an unnecessary level of nesting as the filename seems to be the ultimate primary name key.

**Comment by DavidMarchant** [comment]
You are absolutely correct, this is unnecessary & stands to complicate all parsing and editing of the  yaml files (as well as needlessly indenting them an extra level). I'll alter this once I've gotten confirmation on some backwards compatibility stuff.

It's a holdover from the very earliest days of the project I think, when we had >1 asset's data stored in the same file and it was needed to separate the data.

**Comment by ColonelPanicks** [comment]
Thanks for agreeing!

I certainly think there's a concern here regarding the change in formatting but, as you mention, the way we deal with #113 should handle this. The oldest live system is using separate yaml files for nodes so luckily no handling would be needed for the all-in-one yaml setup.

**Comment by DavidMarchant** [comment]
Champion! We'll alter the codebase to expect top-level data at the same time we implement the script mentioned in #113
