### ISSUE TITLE
Command Line Generalisation

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-inventory#127]
Inventoryware has a lot of useful functionality but there is inconsistency in the structure and functionality of the various sub-commands. To prepare for the next release of Flight Inventory (and to provide a clean look for integration with the Alces Appliance) these inconsistencies need to be addressed. 

### List, Create, Delete, Show

Keep as is.

### Modify

Concept: Modify commands should provide either wizards or CLI options for data manipulation.

### Edit

Concept: Edit commands should open interactive vim sessions

### Parse

Concept: To keep in line with other openflight tools (see openflighthpc/flight-cloud) this should be **renamed to import**.

**Comment by mjtko** [comment]
While going through this, I think we should take the opportunity to replace subcommands too, as our current opinion is that these reduce discoverability/usability.  Reckon we replace them with dasherized `modify-xxxx`-style commands a la `virsh` and `ipa`.
