### ISSUE TITLE
Make default store inventory automatically if it doesn't exist

### ISSUE THREAD

**Issue by VoxSecundus** [openflighthpc/flight-inventory#145]
At the moment, trying to `import` new inventory information results in the command line spitting out:
```
Importing data.zip
inventory: Directory /home/root/flight-inventory/var/default not found.
Please create it before continuing.
```
While it's very easy to just `mkdir` the `default` directory, it may be useful to just create that directory if it doesn't exist automatically.

**Comment by benarmston** [comment]
This has been fixed in f2e42caa.
