### ISSUE TITLE
Asset list by type and group

### ISSUE THREAD

**Issue by ste78** [openflighthpc/flight-inventory#93]
Add a `group` switch to the list functionality to be able to see only members of a primary or secondary group

It would also be helpful to have a group concept on the modify functionality, (eg `modify notes allnodes`) as a first pass possibly being simplest to overwrite any member that already have values set with a warning

**Comment by DavidMarchant** [comment]
As for the first point - yeah, sure!
As for the second - there's a possible usability issue there; if you `modify notes allnodes` with n nodes in `allnodes` would you expect to have n separate vim instances open in sequence or have one open & have its results saved for all n nodes? This applies for all commands that involve opening an editor. (`modify notes`, `modify map` & `edit`)
It's also worth noting, if you didn't already know, that the same functionality can already be achieved with `modify other notes=<your_notes_string_here> -g allnodes`

**Comment by ste78** [comment]
definitely wouldn't expect separate vim instances, I think I'd expect a single editor and then it update the field being edited for all members of the group, and in the first pass overwriting anything already set for a member. The use case would usually be to set notes across a group when initially populating them but then editing them individually over time. 

No I didn't realise until after I posted the enhancement that you could do that on the cli with a string, but would still be nice to be able to use editor. Often I'm putting markdown in as notes, doing that as a single line string isn't fun  😎

**Comment by DavidMarchant** [comment]
Ah reet, fair do's! If that's what would be it expected it all sounds good then
Very understandable that an editor is preferred over a cli string

**Comment by ste78** [comment]
aye too reet, nowt like a proper brew
